name: Analyze & Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test & build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: bluefireteam/melos-action@dd3c344d731938d2ab2567a261f54a19a68b5f6a
        with:
          melos-version: "6.0.0"
      ##https://github.com/flutter/flutter/issues/59750#issuecomment-646055197
      - name: Patch for linux build
        run: |
          flutter doctor
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter doctor
      - name: Setup test
        run: melos run build_linux --no-select

      - name: "Set environmental variables"
        run: |
          echo "LIBQUICKJSC_TEST_PATH=${GITHUB_WORKSPACE}/packages/flutter_survey_js/example/build/linux/x64/debug/plugins/flutter_js/bundle/lib/libquickjs_c_bridge_plugin.so" >> $GITHUB_ENV
      - name: Run tests
        run: melos run test --no-select
      - run: |
          cd packages/flutter_survey_js/example
          flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true

#      - name: "Run Analyze"
#        run: melos run analyze

#      - name: "Pub Check"
#        run: |
#          melos exec -c 1 --no-private --ignore="*example*"  -- \
#            flutter pub publish --dry-run
